
#ifndef _TASK_DEFINE_ED_H
#define _TASK_DEFINE_ED_H

#include <iostream>

typedef enum {
	NEW = 0,
	PENDING,
	DISPATCH,
	DISPATCHED,
	CHECK,
	ONGOING,
	REJECTED,
	FAILED,
	ABORTED,
	FORCE_COMPLETED,
	DONE,
	CHARGING
}SUB_TASK_STATUS;


typedef enum {
	AGV_RESPONSE_SUCC = 1,
	AGV_RESPONSE_FAILED = 2
}AGV_RESPONSE_WC;

typedef enum {
	TRAY = 0,
	GOODS = 1
}CageType;

typedef enum {
	IN_STORAGE = 1,
	OUT_STORAGE = 0
}WorkType;

typedef enum {
	BEGIN_GET = 1,
	GET_OVER = 2
}AGV_RESPONSE_RECEIVING;

typedef enum {
	AGV_TASK = 0,

	//DIRECT_FORWARD_GET = 11,			//正向行走并取货;
	//DIRECT_FORWARD_PUT = 12,			//正向行走并放货;
	//DIRECT_FORWARD_PATH = 13,			//直接去;
	//DIRECT_BACKWARD_PATH = 14,			//直接倒车去;
	//AGV_IN_SITU_CHARGING = 499,			//原地充电;
	//BACKWARD_GET = 15,                  //倒车去取货;
	//BACKWARD_PUT = 16,					//倒车去放货;
	//	T_FORWARD_BACKWARD = 3003,          //T车正向行走后再倒车;
	//L_FORWARD_BACKWARD = 3007           //L车正向行走后再倒车;

	DIRECT_FORWARD_GET = 1111,				//正向行走并取货;
	DIRECT_FORWARD_PUT = 1112,				//正向行走并放货;
	DIRECT_FORWARD_PATH_NOT_FORK = 1000,				//直接去;
	DIRECT_FORWARD_PATH = 1001,				//直接去;
	DIRECT_BACKWARD_PATH = 1002,			//直接倒车去;
	FORCE_FORWARD_BACKWARD = 1003,			// 强行倒车入库
	FORWARD_BACKWARD_TO_STORAGE_HEIGHT = 1134,			// 倒车入库同步升叉到库位高度
	AGV_IN_SITU_CHARGING = 1040,			//原地充电;
	FAKE_AGV_IN_SITU_CHARGING = 1041,		//假原地充电;
	AGV_IN_SITU_CHARGING_STOP = 1043,		//原地断电;
	BACKWARD_GET = 1113,					//倒车去取货;
	BACKWARD_PUT = 1114,					//倒车去放货;
	FORWARD_STACK_PUT = 1108,				//正向行走并二层及以上堆叠放货;
	FORWARD_STACK_GET = 1109,				//正向行走并二层及以上堆叠取货;
	FORWARD_BACKWARD = 1005,				//正向行走后再倒车;
	FORK_DOWN_FORWARD_BACKWARD = 1116,	    //正向行走后再倒车;
	DIRECT_FORWARD_DOWN_FORK = 1117,        //正向行走到站点并降叉到库位高度;
	PARKING_FORWARD = 1004,        //停车任务，正向进入停车点，车头朝里
	LOCAL_WAITING_WARNING = 1055,
	LANDMARK_BEGIN_TASK = 1050,
	WEIGHTING_TASK = 1056,                  //称重任务
	LANDMARK_STOP_TASK = 1051,
	FAKE_DIRECT_FORWARD_GET = 1120,          //虚拟取货任务
	LOCAL_DOWN_FORK = 1013,

	FORK_DOWN = 1127,

}SUB_TASK_TYPE;


typedef enum {
	NONE_TASK = 0,
	CARRY_TASK = 1,
	PARKING_TASK = 2,
	CHARGING_TASK = 3,
	STACK_TASK = 4

}TASK_CHAIN_TYPE;


typedef enum {
	NONE = 0,
	BLOCKED,
	BEGIN,
	PARKING,
	BEGING_CHARGING,
	IS_CHARGING,

	PARKING_BUFFER,
	PARKING_BUFFER_CHECK,

	PARKING_RELEASE,
	PARKING_RELEASE_CHECK,

	TO_PARKING_RELEASE,
	TO_PARKING_RELEASE_CHECK,

	PARKING_TURN,
	PARKING_TURN_CHECK,

	GET_GOODS_BUFFER_CONFIRM,
	GET_GOODS_BUFFER_CONFIRM_CHECK,
	PUT_GOODS_BUFFER_CONFIRM,
	PUT_GOODS_BUFFER_CONFIRM_CHECK,
	GET_GOODS_BUFFER_RELEASE,
	GET_GOODS_BUFFER_RELEASE_CHECK,
	PUT_GOODS_BUFFER_RELEASE,
	PUT_GOODS_BUFFER_RELEASE_CHECK,

	X_CONFIRM,
	X_CONFIRM_CHECK,
	X_RELEASE,
	X_RELEASE_CHECK,

	GOTO_CURRENT_BUFFER_RELEASE,
	GOTO_CURRENT_BUFFER_RELEASE_CHECK,
	GOTO_START_BUFFER_CONFIRM,
	GET_TRAY_BUFFER_CONFIRM,
	GET_TRAY_BUFFER_CONFIRM_CHECK,
	TRAY_RELEASE,
	TRAY_RELEASE_CHECK,
	TRAY_BUFFER_RELEASE,
	TRAY_BUFFER_RELEASE_CHECK,

	EQUIP_GET,
	EQUIP_GET_CHECK,
	BUFFER_PUT,
	BUFFER_PUT_CHECK,
	BUFFER_GET,
	BUFFER_GET_CHECK,

	WAIT_AREA,
	WAIT_AREA_CHECK,

	EXIT_BUFFER,
	EXIT_BUFFER_CHECK,
	EQUIP_PUT,
	EQUIP_PUT_CHECK,
	EQUIP_PUT_CONFIRM,
	EQUIP_PUT_CONFIRM_CHECK,
	B_EQUIP_PUT_CONFIRM,
	B_EQUIP_PUT_CONFIRM_CHECK,
	EQUIP_PUT_RELEASE,
	EQUIP_PUT_RELEASE_CHECK,
	EQUIP_PUT_RELEASE_DOWN_FORK,
	EQUIP_PUT_RELEASE_DOWN_FORK_CHECK,
	EQUIP_GET_CONFIRM,
	EQUIP_GET_CONFIRM_CHECK,

	EQUIP_GET_RELEASE,
	EQUIP_GET_RELEASE_CHECK,
	EQUIP_GET_RELEASE_DOWN_FORK,
	EQUIP_GET_RELEASE_DOWN_FORK_CHECK,
	BEGIN_CHECK,
	PARKING_CHECK,
	OVER,
	ABORT,
	ERR
}TASK_CHAIN_STATUS;


typedef enum {

	CHANRING_PENDING,
	CHARGING_PAUSE,
	CHANRING_FAILED,
	CHANRING_CHARGING,
	CHANRING_STOP
}CHARGING_STATUS;

//typedef enum {
//	
//	B_CONFIRM_ = 11,
//	C_CONFIRM_ = 12,
//	D_CONFIRM_ = 13,
//
//	B_CONFIRM = 41,
//	C_CONFIRM = 42,
//	D_CONFIRM = 43,
//
//	B_MIDDLE = 21,
//	C_MIDDLE = 22,
//	D_MIDDLE = 23,
//
//	B_FAR = 31,
//	C_FAR = 32,
//	D_FAR = 33,
//
//	B_AREA = 1,
//	C_AREA = 2,
//	D_AREA = 3,
//}CONFIRM;

//#define B_CONFIRM_  "11"
//#define C_CONFIRM_  "12"
//#define D_CONFIRM_  "13"

#define A_AREA "A_AREA"

#define B_CONFIRM  "B_CONFIRM"
#define C_CONFIRM  "C_CONFIRM"
#define D_CONFIRM  "D_CONFIRM"

#define B_MIDDLE  "B_MIDDLE"
#define C_MIDDLE  "C_MIDDLE"
#define D_MIDDLE  "D_MIDDLE"

#define B_FAR  "B_FAR"
#define C_FAR  "C_FAR"
#define D_FAR  "D_FAR"

#define B_AREA "B_AREA"
#define C_AREA "C_AREA"
#define D_AREA "D_AREA"


typedef enum {
	BEGING_INVOKE,
	STOP_INVOKE

}INVOKE_STATUS;
typedef struct _Task_Data
{
	int mean;
	int noise_deviation;
	std::string from;
	std::string to;

}Task_Data;

typedef struct _Task_Chain_Info
{
	std::string ORDER_ID_;
	std::string START_;
	std::string START_CONFIRM_;
	std::string TARGET_;
	std::string TARGET_CONFIRM_;
	int PRIORITY_;
	TASK_CHAIN_STATUS Status_;
	std::string STATUS_;
	std::string MODE_;
	std::string TYPE_;
	int AGV_ID_;
	std::string Timestamp_;
	std::string SYSTEM_;
	std::string PALLETNO_;
}Task_Chain_Info;

#endif //_TASK_DEFINE_ED_H